Vfd 113 tmt api kayttoonotto
Virtual-Finland-Development/tmt-productizer pull request #16
Opened 2022-11-16 19:37 UTC by lsipii

- Adds an access flow to TMT API by using AWS Secrets Manager
  - running locally with live data needs an AWS CLI profile setup
- removes the prism "datanator" from the default configuration
  - still accessible by using `docker-compose.prism.yml` -file, which runs in a mock-mode
  - running in a mock-mode disables the authentication requests
- updates README

2022-11-17 07:15 UTC, lassipatanen requested changes

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer.UnitTests/Services/JobServiceTests.cs
> +        var mockTMT_AuthorizationService = new MockTMT_AuthorizationService();
Luokkien nimissä voisi noudattaa `CamelCase` nimeämistä ja muuttujissa `lowerCamelCase`

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer.UnitTests/Services/JobServiceTests.cs
> +public class MockTMT_AuthorizationService : ITMT_AuthorizationService
Tämä kannattaisi varmaan mockata käyttäen Moq metodeita esim:

`var tmtAuthorizationService = new Mock<ITmtAuthorizationService>();
tmtAuthorizationService.Setup(service => service.GetTMTAuthorizationDetails()).Returns(Task.FromResult(
            new TMTAuthorizationDetails
            {
                AccessToken = It.IsAny<string>(),
                ProxyAddress = It.IsAny<string>(),
                ProxyUser = It.IsAny<string>(),
                ProxyPassword = It.IsAny<string>()
            }));`

Ja jos haluaa välttää tuon toistamista, jos noilla arvoilla ei ole testien kannalta mitään väliä, voi tuon tehdä SetUp osiossa ja asettaa muuttujaan, jolloin sitä objetia voi käyttää kaikissa testeissä.

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/appsettings.json
>    "AppConfig": {
AppConfig osio appsettings tiedoston sisällä kuulostaa vähän turhalta.

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Services/JobService.cs
> +    private HttpClient getTMTProxyClient(TMTAuthorizationDetails tmtAuthorizationDetails)
C# nimeämiskäytäntö taitaa yleisesti olla:
Funktioiden nimet `CamelCase`
muuttujat `lowerCamelCase`
privaatit muuttujat `_` prefixillä, mikä vähentää tarvetta viljellä `this` keywordiä

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Services/JobService.cs
> +    private HttpClient getTMTProxyClient(TMTAuthorizationDetails tmtAuthorizationDetails)
Siirtäisin myös tämän funktion myös omaan luokkaansa ClientFactory tjs missä hanskataan oikeanlaisen HttpClientin luominen. Nyt Program.cs filussa rekisteröidään HttpClient turhaan, kun sitä clienttiä ei käytettä muuhun kuin BaseAddress lukemiseen.

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Services/TMT/TMT_AuthorizationService.cs
> +        if (this._skipAuthorizationCeck) return new TMTAuthorizationDetails();
thissit on turhia

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Services/TMT/TMT_AuthorizationService.cs
> +    public TMT_AuthorizationService(HttpClient client, ISecretsManager secretsManager, ILogger<TMT_AuthorizationService> logger, IWebHostEnvironment env)
`IWebHostEnvironment` voi olla `IHostEnvironment`

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Models/TMT_API.cs
> +    public string? ClientId { get; set; }
Voiko tämä ikinä olla null? Koodissa katsotaan secrettien hakemisen jälkeen, onko tämä null ja palautetaan virhe, mutta eikä json deserialize heittäisi jo aikaisemmin virheen, jos tätä arvoa ei pystytä asettamaan?

Paitsi toki jos halutaan erikseen saada tietää onko client_id asettamatta.

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Models/TMT_API.cs
> +    [JsonPropertyName("CLIENT_SECRET")]
Sama tässä

2022-11-17 07:15 UTC, lassipatanen commented on src/TMTProductizer/Services/AuthorizationService.cs
> +    public AuthorizationService(HttpClient client, IWebHostEnvironment env)
IWebHostEnvironment  voi olla IHostEnvironment

2022-11-18 07:31 UTC, lassipatanen approved these changes
Hyvää duunia! 👍

2022-11-18 07:31 UTC, lassipatanen commented on src/TMTProductizer.UnitTests/Services/JobServiceTests.cs
> +    private string GetTMTTestResponse()
👍

2022-11-18 07:31 UTC, lassipatanen commented on src/TMTProductizer/Services/TMT/TMTAuthorizationService.cs
> +        _TMTAuthorizationDetails = await GetchTMTAuthorizationDetails();
Onko tässä typo vai getin ja fetchin yhdistelmä? :D

2022-11-18 08:00 UTC, lsipii commented on src/TMTProductizer/Services/TMT/TMTAuthorizationService.cs
> +        _TMTAuthorizationDetails = await GetchTMTAuthorizationDetails();
Jotenkin tulee mieleen hahmo Gerry sarjasta Parks & Recreation.

2022-11-18 08:01 UTC, merged