Vfd 161 tmt producitzer tyonhakufilttereihin isco esco laajennos
Virtual-Finland-Development/tmt-productizer pull request #30
Opened 2022-12-20 15:49 UTC by lsipii

if the occupation URI is a category, filter by its sub-occupations

2022-12-20 16:22 UTC, lsipii commented on src/TMTProductizer/Utils/Request/JobsRequestParser.cs
> +    private List<string> GetSubOccupationURIs(string parentOccupationURI, List<OccupationCodeSet.Occupation> occupations)
Tähän voisi sopia hyvin se RDF-graafikirjasto ja sen työkalut.

2022-12-20 16:26 UTC, lsipii commented on src/TMTProductizer/Data/Repositories/OccupationCodeSetRepository.cs
> +        using var reader = new StreamReader("Data/RawData/esco-1.1.0-occupations.json");
Tämä olisi hyvä tulla jostain meidän omasta jaettujen resurssien palvelusta jota ei tähän hätään vielä ole.

2022-12-21 11:02 UTC, lassipatanen requested changes
Muutaman kommentin jätin... jos on mitään kysyttävää niistä niin voidaan katsoa yhdessä läpi.

2022-12-21 11:02 UTC, lassipatanen commented on src/TMTProductizer/Program.cs
> +                TotalCount = jobs.Count,
Itselleni ei ihan aukea tämän muutoksen tarkoitus? Miksi total count on yhden sivun tulosten määrä? Client voi varmasti tarvittaessa itse laskea tuon results countin?

2022-12-21 11:02 UTC, lassipatanen commented on src/TMTProductizer/Utils/Request/JobsRequestParser.cs
> +    private readonly ILogger<IRequestParser<JobsRequest>> _logger;
_loggeria ei ikinä käytetä missään

2022-12-21 11:02 UTC, lassipatanen commented on src/TMTProductizer/Utils/Request/JobsRequestParser.cs
> +        if (request.Requirements != null && request.Requirements.Occupations != null && request.Requirements.Occupations.Any())
Kaksi ensimmäistä tarkistusta lienee turhia, kun nuo objektit eivät ole nullable

2022-12-21 11:02 UTC, lassipatanen commented on src/TMTProductizer/Utils/Request/JobsRequestParser.cs
> +    public async Task<JobsRequest> Parse(JobsRequest request)
Varmasti toimii näinkin, mutta mielestäni on ehkä vähän huono tapa muuttaa request objektia sen sijaan että tekisi tämän muutoksen siellä, missä tuota koodia tarvitaan.

2022-12-21 13:36 UTC, LauriGofore approved these changes
laajennus toimi ainakin oman testauksen perusteella, että siltä osin: approve.

2022-12-21 15:10 UTC, lsipii commented on src/TMTProductizer/Program.cs
> +                TotalCount = jobs.Count,
Joo oikein aukeamattomaksi nähty: tässä on ollut lähinnä debug-tarkoituksiin tulosten tarkastelun avustus käynnissä ja ei kuulu tähän pr:ään: totalCount pitäisikin olla se luku mikä tulee haetuista otsakkeista ennen filtteröintiä.

2022-12-21 15:17 UTC, lsipii commented on src/TMTProductizer/Utils/Request/JobsRequestParser.cs
> +        if (request.Requirements != null && request.Requirements.Occupations != null && request.Requirements.Occupations.Any())
Lintteri ei tunnu aina päivittyvän ja tässä tapauksessa on vänissyt turhista. Mutta: [data-definitionissa](https://github.com/Virtual-Finland/definitions/blob/main/DataProducts/test/lassipatanen/Job/JobPosting.json) kaikki noi `JobsRequest` -objektin arvot ovat valinnaisia (ei ole required-määritystä) eli se ei reflektoidu toteutuksessa ihan oikein.

2022-12-21 15:37 UTC, lsipii commented on src/TMTProductizer/Utils/Request/JobsRequestParser.cs
> +    public async Task<JobsRequest> Parse(JobsRequest request)
Tässä on taustalla mantra "parse, dont validate", mutta tosiaan parserin pitäisi olla immutable. 

Request-inputin varmistaminen/parsiminen ja tässä tapauksessa täydentäminen on iha ok tehdä controller-tasolla: ei se oikein nätisti mahdu tiedon haku/käsittelypalveluiden vastuisiin kun siellä jo on muutakin tekemistä.

Inputin täydentämisestä tässä tapuksesas vielä että tämä täydentäminen olisi ajatustasolla tehtävissä myös apia kutsuvassa clientissä, mutta helpottamaan menoa tehdään se api-päässä inputin käsittelyvaiheessa.

2022-12-22 11:52 UTC, lsipii commented
Siirretään tämä toteutus kutsujan puolelle testbed-api:n vastuuksi.

2022-12-22 11:52 UTC, closed without merging